config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about'=> 'homes#about'
  get '/search', to: 'cars#search'
  get 'chat/:id' => 'chats#show', as: 'chat'
  get 'user/out' => 'users#out'
  patch 'user/with_out' => 'users#with_out'
  resources :chats, only: [:create]
  resources :cars, only: [:index, :show, :new, :create]
  resources :users, only: [:index, :show,:edit, :update]
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :notifications
  validates :first_name, :last_name, :first_name_kana, :last_name_kana, :age, :first_address, :last_address, :email, presence: true
  enum address: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(@user)
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end
  def show
    @user = User.find(params[:id])
    @cars = @user.cars
  end
  def out
  end
  def with_out
    @user = current_user
    @user.update(is_active: false)
    # 退会機能もupdate
    reset_session
    redirect_to root_path
  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :age, :last_address, :email)
    # (user_params)とアクションの後ろにつけることでrequireのpermit(カラム)を変更したりできる
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='container'>
 <div class='row'>
  <div class="mx-auto">
   <h1>会員情報編集<i class="fas fa-user"></i></h1>
   <% if @user.errors.any? %>
  　<%= @user.errors.count %>件のエラーが発生しました
  　<% @user.errors.full_messages.each do |message| %>
     <%= message %>
  　<% end %>
　 <% end %>
   <%= form_with model: @user, url:user_path(@user) , local: true do |f| %>
   <table class="table">
    <tr>
     <th>氏名</th>
     <td><%= f.text_field :first_name, :placeholder => "(姓)" %></td>
     <td><%= f.text_field :last_name, :placeholder => "(名)" %></td>
     <td></td>
    </tr>
    <tr>
     <th>フリガナ</th>
     <td><%= f.text_field :first_name_kana, :placeholder => "(セイ)" %></td>
     <td><%= f.text_field :last_name_kana, :placeholder => "(メイ)" %></td>
     <td></td>
    </tr>
    <tr>
     <th>年齢</th><td><%= f.text_field :age %>歳</td><td></td><td></td>
    </tr>
    <tr>
     <th>出身</th><td><%= User.addresses.key(@user.first_address) %></td>
     <th>現住所</th><td><%= f.select :last_address, User.addresses, {prompt: '選択してください'} %></td>
    </tr>
    <tr><th>e-mail</th><td><%= f.text_field :email, size: "30" %></td><td></td><td></td></tr>
   </table>
   <foot>
    <%= f.submit "保存する", class: "btn btn-primary" %>
    <% if current_user == @user %><%= link_to "退会する" , user_out_path, class: "btn btn-danger" %><% end %>
   </foot>
   <% end %>
  </div>
 </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class='col-md-8 offset-md-1'>
   <br />
   <h1>会員一覧<i class="fas fa-user"></i></h1>
   <table class="table table-hover">
    <thead>
     <tr class="table-secondary">
      <th>ID</th>
      <th>名前</th>
      <th>年齢</th>
      <th>status</th>
     </tr>
    </thead>
    <tbody>
     <% @users.each do |user| %>
      <tr>
       <td><%= user.id %></td>
       <td>
        <% if current_user == user %>
         <%= link_to user.first_name + user.last_name, user_path(user.id), class: 'text-success' %>
        <% else %>
         <%= link_to user.first_name + user.last_name, user_path(user.id), class: 'text-secondary' %>
        <% end %>
       </td>
       <td><%= user.age %></td>
       <td><% if user.is_active %><p class="text-dark">有効</p><% else %><p class="text-danger">退会</p><% end %></td>
      </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/out.html.erb
<div class='container'>
 <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <br /><br />
   <h4>本当に退会しますか？</h4>
   <br /><br />
   <strong>
    退会すると、会員登録情報や<br />これまでの購⼊履歴が閲覧できなくなります。<br />退会する場合は、「退会する」をクリックしてください。
   </strong>
   <br /><br />
    <%= link_to "退会しない" , user_path(current_user.id), class: "btn btn-primary" %>
    <%= link_to "退会する" , user_with_out_path, method: :patch, class: "btn btn-danger", data: { confirm: "【確認】アカウントを削除してもよろしいですか？" } %>
    <!--まずトップに飛ばす前にキャンセルに飛ばすトップに飛ばすのはコントローラーで指定する-->
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class='container'>
 <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>
    会員情報
    <i class="fas fa-user"></i>
    <% if current_user == @user %>
     <%= link_to "編集する", edit_user_path(@user), class: "fas fa-user-cog btn btn-success" %>
    <% end %>
   </h1>
   
   <table class="table">
    <tr><th>氏名</th><td><%= @user.first_name + @user.last_name %></td></tr>
    <tr><th>カナ</th><td><%= @user.first_name_kana + @user.last_name_kana %></td></tr>
    <tr><th>年齢</th><td><%= @user.age %></td></tr>
    <tr><th>出身</th><td><%= User.addresses.key(@user.first_address) %></td></tr>
    <tr><th>現住所</th><td><%= User.addresses.key(@user.last_address) %></td></tr>
    <tr><th>メールアドレス</th><td><%= @user.email %></td></tr>
   </table>
   
   <table class="table table-hover">
    <thead>
     <tr class="table-secondary">
      <th>ID</th>
      <th>名前</th>
      <th>ボディ</th>
      <th>メーカー</th>
     </tr>
    </thead>
    <% if @user.is_active %>
     <% if current_user == @user %><% else %><%= link_to 'DMを送る', chat_path(@user.id)%><% end %>
    <% else %>
     <p>このユーザーは退会済みなのでDMが送れません</p>
    <% end %>
    <tbody>
     <% @cars.each do |car| %>
      <tr>
       <td><%= car.id %></td>
       <td><%= link_to car.car_name, car_path(car.id), class: "car_name", data: { car_id: car.car_name, maker_body: car.maker + car.body_type } %></td>
       <td><%= car.body_type %></td>
       <td><%= car.maker %></td>
      </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>