config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about'=> 'homes#about'
  get '/search', to: 'cars#search'
  get 'chat/:id' => 'chats#show', as: 'chat'
  get 'user/out' => 'users#out'
  patch 'user/with_out' => 'users#with_out'
  resources :chats, only: [:create]
  resources :cars, only: [:index, :show, :new, :create]
  resources :users, only: [:index, :show,:edit, :update]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    def self.search(keyword)
        where(["maker like? OR body_type like?", "%#{keyword}%", "%#{keyword}%"])
    end
    enum maker: { TOYOTA: 0, HONDA: 1, NISSAN: 2, MAZDA: 3, other: 5 }
    enum body_type: { コンパクト: 0, ミニバン: 1, セダン: 2, スポーツ: 3, 軽自動車: 4, その他: 5 }
    has_many :favorites, dependent: :destroy
    belongs_to :user
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
    validates :maker, presence: true
    validates :body_type, presence: true
    validates :car_name, presence: true
    validates :star, numericality: {
        less_than_or_equal_to: 5,
        greater_than_or_equal_to: 0
    }, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :car
end

app/models/notification.rb
class Notification < ApplicationRecord
    belongs_to :chat
    belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :user_rooms
    has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :notifications
  validates :first_name, :last_name, :first_name_kana, :last_name_kana, :age, :first_address, :last_address, :email, presence: true
  enum address: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :get_notifications, if: :user_signed_in?
  
  def after_sign_up_path_for(resource)
      users_path
  end

  def after_sign_out_path_for(resource)
      root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :age, :first_address, :last_address, :email, :password, :password_confirmation])
  end
  
  def get_notifications
   @notifications = current_user.notifications
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
      @cars = Car.all
  end
  def new
    @car = Car.new
  end
  def create
    @car = Car.new(car_params)
    @car.user_id = current_user.id
    # binding.pry
    if @car.star.blank?
      @car.star = 0
    end
    if @car.car_name.blank?
      @car.car_name = "その他"
    end
    # @car.save!
    # redirect_to cars_path, notice: '保存が成功しました'
    if @car.save
      redirect_to cars_path, notice: '保存が成功しました'
    else
      render "new"
    end
  end
  def show
    @car = Car.find(params[:id])
    @user = User.find(@car.user_id)
  end
  def search
    maker_ids = []
    regexp = Regexp.new(".*#{params[:keyword].downcase}.*")
    Car.makers.each do |name, value|
      if name.downcase.match(regexp)
        maker_ids << value
      end
    end
    body_type_ids = []
    Car.body_types.each do |name, value|
      if name.downcase.match(regexp)
        body_type_ids << value
      end
    end
    @cars = Car.where('maker IN (?) OR body_type IN (?) OR car_name like?', maker_ids, body_type_ids, "%#{params[:keyword]}%")
    @keyword = params[:keyword]
    render "cars/index"
  end
  private
  def car_params
    params.require(:car).permit(:maker, :other_maker, :body_type, :car_name, :star, :color, :review).merge(params.permit(:car_name))
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
    def show
        @user = User.find(params[:id])
        if @user.is_active
            if @user == current_user
                flash[:notice] = '※無効な操作です'
                redirect_to root_path
            end
            rooms = current_user.user_rooms.pluck(:room_id)
            user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
            unless user_rooms.nil?
                @room = user_rooms.room
            else
                @room = Room.new
                @room.save
                UserRoom.create(user_id: current_user.id, room_id: @room.id)
                UserRoom.create(user_id: @user.id, room_id: @room.id)
            end
            @chats = @room.chats
            @chat = Chat.new(room_id: @room.id)
        else
            redirect_to user_path(current_user)
        end
    end
    def create
        @chat = current_user.chats.new(chat_params)
        if @chat.save
            Notification.create!(chat_id: @chat.id, user_id: params[:chat][:user_id])
            redirect_to request.referer
        end
    end
    private
    def chat_params
        params.require(:chat).permit(:message, :room_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        @car = Car.find(params[:format])
        favorite = current_user.favorites.new(car_id: @car.id)
        favorite.save
        redirect_to car_path(@car)
    end
    def destroy
        @car = Car.find(params[:id])
        favorite = current_user.favorites.find_by(car_id: @car.id)
        favorite.destroy
        redirect_to car_path(@car)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(@user)
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end
  def show
    @user = User.find(params[:id])
    @cars = @user.cars
  end
  def out
  end
  def with_out
    @user = current_user
    @user.update(is_active: false)
    # 退会機能もupdate
    reset_session
    redirect_to root_path
  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :age, :last_address, :email)
    # (user_params)とアクションの後ろにつけることでrequireのpermit(カラム)を変更したりできる
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarAccess</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
    <nav class="navbar navbar-expand-lg bg-primary">
     <div class="container">
      <a class="navbar-brand"><%= link_to "Car Access", root_path, class: "nav-link text-light" %></a>
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <% if user_signed_in? %>
         <ul class="navbar-nav ml-auto">
        <li>
         <div class="doropdown-box">
          <div style="position:relative">
           <i class="far fa-bell nav-link text-light" style="position:absolute;font-weight:bold;color:white;font-weight:bold;width:114px;">Message</i>
           <span style="width:8px;height:8px;color:orange;background-color:orange;border-radius:50%;position:absolute;top:6px;left:18px;"></span>
          </div>
          <div class="dropdown" style="width:114px;">
           <button style="opacity:0;" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
           <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <% @notifications.each do |notification| %>
             <a class="dropdown-item" href="#">
              <%= link_to notification.chat.user.first_name + notification.chat.user.last_name, chat_path(notification.chat.user.id) %>さんからDMが届いてます
             </a>
            <% end %>
           </div>
          </div>
         </div>
        </li>
        <li><%= link_to "About",home_about_path, class: "fas fa-link nav-link text-light" %></li>
        <li><%= link_to "Users",users_path, class: "fas fa-users nav-link text-light" %></li>
        <li><%= link_to "Cars",cars_path, class: "fas fa-car nav-link text-light" %></li>
        <li><%= link_to "logout", destroy_user_session_path,class: "fas fa-sign-out-alt nav-link text-light", method: :delete %></li>
       </ul>
       <div class="actions">
        <%= form_with url: search_path, method: :get, local: true do |f| %>
         <%= f.text_field :keyword, :placeholder => "Search", value: @keyword %>
         <%= f.button :type => "submit", style: 'border-style: none;' do %><i class='fas fa-search btn btn-secondary'></i><% end %>
        <% end %>
       </div>
       <% else %>
       <ul class="navbar-nav ml-auto">
        <li><%= link_to "About",home_about_path, class: "fas fa-link nav-link text-light" %></li>
        <li><%= link_to "sign up",new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
        <li><%= link_to "login",user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %></li>
       </ul>
       <% end %>
      </div>
     </div>
    </nav>
   </header>
   <main><%= yield %></main>
   <footer><div class="footer-text">Car<i class="fas fa-car"></i><strong>Access</div></footer>
  </body>
</html>